In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = tf.data.Dataset.range(10)
for x in dataset:
    print(x.numpy())

0
1
2
3
4
5
6
7
8
9


In [4]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
for windowed_data in dataset:
    for y in windowed_data:
        print(y.numpy(), end="")
    print("")

01234
12345
23456
34567
45678
56789
6789
789
89
9


In [5]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(3, shift=1, drop_remainder=True)
for windowed_data in dataset:
    for y in windowed_data:
        print(y.numpy(), end="")
    print("")

012
123
234
345
456
567
678
789


In [6]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for y in dataset:
    print(y.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [7]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x, y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [8]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x, y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[4 5 6 7] [8]
[3 4 5 6] [7]
[5 6 7 8] [9]


In [10]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(3)
for x, y in dataset:
    print(x.numpy(), y.numpy())

[[4 5 6 7]
 [2 3 4 5]
 [5 6 7 8]] [[8]
 [6]
 [9]]
[[0 1 2 3]
 [1 2 3 4]
 [3 4 5 6]] [[4]
 [5]
 [7]]
